### ISSUE TITLE
Feature Request: Allow RS232 servers.

### ISSUE THREAD

**Issue by jamestalmage** [WillCodeForCats/tekmar-packetserv#26]
It would be great to allow RS232 to Ethernet devices. Like [this one](https://www.amazon.com/gp/product/B07G5P4CPR). There's a RS232-only version that only costs $25 (I assume it performs just as well as the RS232/RS485/RS422 version I bought).

From what I can tell, the device works great, no caveats. I started on a basic Homebridge plugin for the 482 before thinking to check if something was available for HA (python noob, so I default to JS).  I modeled it off the same python toolkit from Tekmar that it looks like you modeled yours after. I think the conversion would be pretty easy. Just open a TCP socket and start reading and writing bytes the way you do now, just to a socket instead of a serial port.

I almost think you should move most of the packetserve code into the main plugin (the tekmar specific stuff: byte stuffing, escaping, packetizing, etc), and just have packetserv essentially be a dumb serial-to-ethernet device like the one I bought above. Users could use `packetserve` for non-Tekmar RS232/485 devices, and purchasers of serial-to-ethernet devices could avoid needing to install that add-on entirely. (just a thought)

Back to the main request - It would be great to make this work with 3rd party ethernet-to-serial devices

**Comment by WillCodeForCats** [comment]
I will look into it. I normally use Perle serial servers.

> I almost think you should move most of the packetserve code into the main plugin (the tekmar specific stuff: byte stuffing, escaping, packetizing, etc), and just have packetserv essentially be a dumb serial-to-ethernet device like the one I bought above. Users could use packetserve for non-Tekmar RS232/485 devices, and purchasers of serial-to-ethernet devices could avoid needing to install that add-on entirely. (just a thought)

There are already other projects out there that do dumb serial to Ethernet stuff, so duplicating that work is not something I'd care to do. At the moment I prefer to follow the model that Z-Wave JS has taken: an integration for HA core with an add-on to interface with the hardware.

In its current state it also works with one-to-many applications: multiple integrations can connect to a single `tekmar-packetserv` simultaneously. That would not be possible if packet processing was moved into the integration.

**Comment by jamestalmage** [comment]
> In its current state it also works with one-to-many applications: multiple integrations can connect to a single tekmar-packetserv simultaneously. That would not be possible if packet processing was moved into the integration.

A fair point. The USR device has settings for max connected clients, and a checkbox for whether new connections should boot off old connections. No explanation for how it handles data flow for multiple connected clients. I assume it mirrors data from the serial bus to all connected, and queues writes based on TCP packet boundaries.... But that's a big assumption

**Comment by WillCodeForCats** [comment]
Yeah but that's very device-specific, and how your device handles it isn't necessarily how mine will or any other number of random ones out there someone might want to use. And I don't really have any desire to make some elaborate system to try and arbitrate all the different possibilities when how it's currently designed has been stable and reliable.

**Comment by WillCodeForCats** [comment]
Added in version 1.2.0
